# Cake Bitbucket Pipeline
image: devlead/bitbucket-pipelines-dotnet

pipelines:
  default:
    - step:
        script:
          - ln -s /opt/dotnet .dotnet
          - mkdir tools
          - ln -s /opt/nuget/nuget.exe ./tools
          - cake --target="Run-Unit-Tests"
